volumes:
  dbdata: {}
  frontend_dist: {}
services:
  django:
    &django
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: project
    volumes:
      - ./backend:/home/user/app/backend:rw
    env_file:
      - ./.envs/local/.django
    ports:
      - 8001:8000
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    env_file:
      - ./.envs/local/.django
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
  frontend:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    volumes:
      - ./Frontend:/app:rw
      - frontend_dist:/app/dist:rw
    ports:
      - 3000:3000
    
    depends_on:
      - django
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile-nginx
    restart: always
    volumes:
      - ./backend/static:/backend/static
      - frontend_dist:/frontend/dist:rw
    ports:
      - 80:80
    depends_on:
      - django
  celery:
    <<: *django
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app:rw
    depends_on:
      - django
      - redis
    ports: []
    entrypoint: []

  celery-beat:
    <<: *django
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app:rw
    depends_on:
      - django
      - redis
    ports: []
    entrypoint: []
    
  redis:
    image: "redis:alpine"
    ports: []

    
